version: '3.1'

services:
  db:
    image: mariadb
    platform: linux/arm64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: money_transfer_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    platform: linux/arm64
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
